# Generated by Django 5.2.7 on 2025-10-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Your code snippet or note content')),
                ('category', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('react', 'React'), ('django', 'Django'), ('nodejs', 'Node.js'), ('sql', 'SQL'), ('git', 'Git'), ('general', 'General'), ('other', 'Other')], default='general', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Optional: attach an image or screenshot', null=True, upload_to='note_images/')),
                ('session_id', models.CharField(blank=True, help_text="For cookie-based 'My Notes' filtering", max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
