# Generated by Django 5.2.7 on 2025-10-26 01:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner of this note; nullable during migration', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='session_id',
            field=models.CharField(blank=True, help_text='[Legacy] Pre-migration cookie-based ownership', max_length=100, null=True),
        ),
    ]
