# Generated by Django 5.2.7 on 2025-10-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user_alter_note_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(default='General', help_text='Enter any category (e.g., Python, JavaScript, etc.)', max_length=50),
        ),
    ]
